[[ -f "${HOME}/dotfiles/motd/${HOST//.home/}.txt" ]] && cat "${HOME}/dotfiles/motd/${HOST//.home/}.txt"
[[ -f "${HOME}/dotfiles/motd/${HOST//.local/}.txt" ]] && cat "${HOME}/dotfiles/motd/${HOST//.local/}.txt"
export PATH="$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH:/opt/bin"

if sysctl -n machdep.cpu.brand_string 2>/dev/null | grep "Core(TM)2 Duo" > /dev/null; then
  export HOMEBREW_NO_AUTO_UPDATE=1
  export HOMEBREW_BUILD_FROM_SOURCE=1
fi

[[ $TMUX != "" ]] && export TERM="tmux-256color"


if [[ ${TERM_PROGRAM} = "DTerm" ]]; then
  ZSH_THEME="default"
fi

POWERLEVEL9K_MODE='nerdfont-complete'
if [ -f "/usr/local/opt/powerlevel9k/powerlevel9k.zsh-theme" ]; then
  source /usr/local/opt/powerlevel9k/powerlevel9k.zsh-theme
else
  ZSH_THEME="powerlevel9k/powerlevel9k"
fi


if [ -d "${HOME}/.oh-my-zsh" ]; then
  export ZSH="${HOME}/.oh-my-zsh"
elif [ -d '/opt/oh-my-zsh' ]; then
  export ZSH=/Users/jozef/.oh-my-zsh
fi

fpath+=("$ZSH/custom/completion")

# ENABLE_CORRECTION="true"
# COMPLETION_WAITING_DOTS="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"

HIST_STAMPS="yyyy-mm-dd"

plugins=(
  git
  vi-mode
  zsh-syntax-highlighting
)


test $(uname) = "Darwin" && \
  plugins+=(osx)

command -v fzf >/dev/null 2>&1 && \
  plugins+=(fzf)

#command -v docker >/dev/null 2>&1 && \
#  plugins+=(docker docker-compose)

export KEYTIMEOUT=1

source $ZSH/oh-my-zsh.sh

if [ -f "${HOME}/.iterm2_shell_integration.zsh" ]; then
  source "${HOME}/.iterm2_shell_integration.zsh"
fi

# The next line updates PATH for the Google Cloud SDK.
#if [ -f '/Users/jozef/Applications/google-cloud-sdk/path.zsh.inc' ]; then
#  . '/Users/jozef/Applications/google-cloud-sdk/path.zsh.inc'
#  . '/Users/jozef/Applications/google-cloud-sdk/completion.zsh.inc'
#  source <(kubectl completion zsh)
#fi

# Add linuxbrew if it exists
if [ -e '/home/linuxbrew' ]; then
  export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
  export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"
  export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"

  fpath+=("/home/linuxbrew/.linuxbrew/share/zsh/site-functions")
fi



if locale -a | grep "en_US.UTF-8" > /dev/null; then
  export LANG=en_US.UTF-8
  export LC_ALL=en_US.UTF-8
else
  export LANG=en_US.utf8
  export LC_ALL=en_US.utf8
fi


export FZF_LEGACY_KEYBINDINGS=
export FZF_DEFAULT_COMMAND='rg --files --hidden --smart-case --glob "\!.git/*"'

bindkey '^[[1;9C' forward-word
bindkey '^[[1;9D' backward-word
bindkey '^[^[[C' forward-word
bindkey '^[^[[D' backward-word
bindkey '^[[1;2D' backward-char
bindkey '^[[1;2C' forward-char
bindkey '^[OA' up-line-or-beginning-search
bindkey '^[OB' down-line-or-beginning-search
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey '\eOH' beginning-of-line
bindkey '\eOF' end-of-line
bindkey '\e[3~' delete-char

venv() { source ~/.virtualenvs/$1/bin/activate }
autoload _venv
compdef _venv venv

DEFAULT_FOREGROUND=159 DEFAULT_BACKGROUND=239 PROMPT_COLOR=172
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="$ "

POWERLEVEL9K_VCS_GIT_ICON=''
POWERLEVEL9K_VCS_STAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_UNTRACKED_ICON='\u25CF'
POWERLEVEL9K_VCS_UNSTAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='\u2193'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='\u2191'

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time vi_mode virtualenv dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(background_jobs status command_execution_time root_indicator)

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=vcs
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=context

POWERLEVEL9K_TIME_BACKGROUND='110'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='110'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='black'
POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND='220'
POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND='black'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='245'
POWERLEVEL9K_VIRTUALENV_BACKGROUND='blue'
POWERLEVEL9K_VIRTUALENV_FOREGROUND='231'
#POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY='false'
#POWERLEVEL9K_VCS_GIT_HOOKS=(git-detect-changes)
POWERLEVEL9K_STATUS_OK='false'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_SHORTEN_DELIMITER="…"
POWERLEVEL9K_SHORTEN_STRATEGY='truncate_to_first_and_last'
POWERLEVEL9K_VI_INSERT_MODE_STRING='I'
POWERLEVEL9K_VI_COMMAND_MODE_STRING='N'
POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE='true'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='202'
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='231'
POWERLEVEL9K_ETC_ICON=''
POWERLEVEL9K_BACKGROUND_JOBS_ICON='⚙︎'

if [ -f ~/.fzf.zsh ]; then
source ~/.fzf.zsh
fi

PATH="/home/yozy/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/yozy/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/yozy/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/yozy/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/yozy/perl5"; export PERL_MM_OPT;
