export PATH="$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH:/opt/bin"

if sysctl -n machdep.cpu.brand_string | grep "Core(TM)2 Duo" > /dev/null; then
  export HOMEBREW_NO_AUTO_UPDATE=1
  export HOMEBREW_BUILD_FROM_SOURCE=1
fi

export TERM=xterm-256color

if [[ ${TERM_PROGRAM} = "DTerm" ]]; then
  ZSH_THEME="default"
fi

ZSH_THEME="powerlevel9k/powerlevel9k"

if [ -d "${HOME}/.oh-my-zsh" ]; then
  export ZSH="${HOME}/.oh-my-zsh"
elif [ -d '/opt/oh-my-zsh' ]; then
  export ZSH=/Users/jozef/.oh-my-zsh
fi

fpath+=("$ZSH/custom/completion")

# ENABLE_CORRECTION="true"
# COMPLETION_WAITING_DOTS="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"

HIST_STAMPS="yyyy-mm-dd"

plugins=(
  vi-mode
  zsh-syntax-highlighting
)


test $(uname) = "Darwin" && \
  plugins+=(osx)

command -v fzf >/dev/null 2>&1 && \
  plugins+=(fzf)

#command -v docker >/dev/null 2>&1 && \
#  plugins+=(docker docker-compose)

export KEYTIMEOUT=1

source $ZSH/oh-my-zsh.sh

if [ -f "${HOME}/.iterm2_shell_integration.zsh" ]; then
  source "${HOME}/.iterm2_shell_integration.zsh"
fi

# The next line updates PATH for the Google Cloud SDK.
#if [ -f '/Users/jozef/Applications/google-cloud-sdk/path.zsh.inc' ]; then
#  . '/Users/jozef/Applications/google-cloud-sdk/path.zsh.inc'
#  . '/Users/jozef/Applications/google-cloud-sdk/completion.zsh.inc'
#  source <(kubectl completion zsh)
#fi

# Add linuxbrew if it exists
if [ -e '/home/linuxbrew' ]; then
  export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
  export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"
  export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"

  fpath+=("/home/linuxbrew/.linuxbrew/share/zsh/site-functions")
fi



if locale -a | grep "en_US.UTF-8" > /dev/null; then
  export LANG=en_US.UTF-8
  export LC_ALL=en_US.UTF-8
else
  export LANG=en_US.utf8
  export LC_ALL=en_US.utf8
fi


export FZF_LEGACY_KEYBINDINGS=
export FZF_DEFAULT_COMMAND='rg --files --hidden --smart-case --glob "\!.git/*"'

bindkey '^[[1;9C' forward-word
bindkey '^[[1;9D' backward-word
bindkey '^[^[[C' forward-word
bindkey '^[^[[D' backward-word
bindkey '^[[1;2D' backward-char
bindkey '^[[1;2C' forward-char
bindkey '^[OA' up-line-or-beginning-search
bindkey '^[OB' down-line-or-beginning-search
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey '\eOH' beginning-of-line
bindkey '\eOF' end-of-line
bindkey '\e[3~' delete-char

venv() { source ~/.virtualenvs/$1/bin/activate }
autoload _venv
compdef _venv venv

#bindkey -v

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context vi_mode virtualenv dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(background_jobs status root_indicator vcs)
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='245'
POWERLEVEL9K_VIRTUALENV_BACKGROUND='blue'
POWERLEVEL9K_VIRTUALENV_FOREGROUND='231'
POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY='false'
POWERLEVEL9K_VCS_GIT_HOOKS=(git-detect-changes)
POWERLEVEL9K_STATUS_OK='false'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_DELIMITER="…"
POWERLEVEL9K_SHORTEN_STRATEGY='truncate_to_first_and_last'
POWERLEVEL9K_VI_INSERT_MODE_STRING='I'
POWERLEVEL9K_VI_COMMAND_MODE_STRING='N'
POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE='true'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='202'
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='231'
POWERLEVEL9K_ETC_ICON=''
POWERLEVEL9K_BACKGROUND_JOBS_ICON='⚙︎'
#POWERLEVEL9K_MODE='compatible'

if [ -f ~/.fzf.zsh ]; then
source ~/.fzf.zsh
fi



